---
- name: Wait for cloud-init to finish
  ansible.builtin.command: cloud-init status --wait
  changed_when: false

- name: Wait for apt locks to be released
  ansible.builtin.shell: while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do sleep 5; done
  changed_when: false

- name: apt update && upgrade
  ansible.builtin.apt:
    upgrade: "yes"
    update_cache: yes

- name: Install required packages
  ansible.builtin.apt:
    package:
      - net-tools
      - sysstat
      - atop
    state: present
